matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      python:
        - "3.6"
    - os: linux
      dist: bionic
      language: python
      python:
        - "3.7"
    - os: windows
      language: python
      python:
        - "3.6"
    - os: windows
      language: python
      python:
        - "3.7"
notifications:
  email: false
install:
  - pip install -r requirements.txt
before_script:
  - cp .env.example .env
  - python manage.py migrate
script:
  - python manage.py test
sudo: false