language: python
matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      python:
        - "3.6"
    - os: linux
      dist: bionic
      language: python
      python:
        - "3.7"
    # Travis CI doesn't support Python virtual envs on Mac OS X yet, workaround is to use generic and install to system python
    #- os: osx
    #  language: python
notifications:
  email: false
install:
  - pip install -r requirements.txt
before_script:
  - cp .env.example .env
  - python manage.py migrate
script:
  - python manage.py test
sudo: false